using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlueDragon.DuneLight.Core.DTOs.Roster;
using BlueDragon.DuneLight.Core.Interfaces.Roster;
using BlueDragon.DuneLight.Core.Shared;
using BlueDragon.DuneLight.Core.Shared.Exceptions;
using BlueDragon.DuneLight.Infrastructure.Domain.Models.Catalog;
using BlueDragon.DuneLight.Infrastructure.Domain.Models.Roster;
using BlueDragon.DuneLight.Infrastructure.Handlers.Interfaces;
using BlueDragon.DuneLight.Infrastructure.Integrations;

namespace BlueDragon.DuneLight.Infrastructure.Services;

public class CompanyHolidayService : ICompanyHolidayService
{
    private readonly ICompanyHolidayHandler _companyHolidayHandler;
    private readonly ICompanyHandler _companyHandler;
    private readonly IPublicHolidayApiClient _publicHolidayApiClient;

    public CompanyHolidayService(
        ICompanyHolidayHandler companyHolidayHandler, ICompanyHandler companyHandler, IPublicHolidayApiClient publicHolidayApiClient)
    {
        _companyHolidayHandler = companyHolidayHandler;
        _companyHandler = companyHandler;
        _publicHolidayApiClient = publicHolidayApiClient;
    }

    public async Task<List<CompanyHolidayDto>> GetForCompany(Guid organizationId, Guid companyId, int year)
    {
        Company company = await EnsureCompanyExists(organizationId, companyId);
        List<CompanyHoliday> holidays = await _companyHolidayHandler.GetForCompanyByYear(organizationId, companyId, year);
        return holidays.Select(h => ToDto(h, company.Name)).ToList();
    }

    public async Task<CompanyHolidayDto> Create(Guid organizationId, Guid userId, Guid companyId, CompanyHolidayCreateRequest request)
    {
        Company company = await EnsureCompanyExists(organizationId, companyId);

        bool exists = await _companyHolidayHandler.ExistsForDate(organizationId, companyId, request.Date);
        if (exists)
            throw new BusinessRuleException(ErrorCodes.DuplicateHolidayDate, "Poslovnica već ima upisan praznik za taj datum.");

        CompanyHoliday holiday = new CompanyHoliday
        {
            Id = Guid.NewGuid(),
            OrganizationId = organizationId,
            CompanyId = companyId,
            Date = new DateTimeOffset(request.Date.Date, TimeSpan.Zero),
            Name = request.Name,
            IsAutoGenerated = false,
            CreatedAt = DateTimeOffset.UtcNow,
            CreatedBy = userId
        };

        await _companyHolidayHandler.Add(holiday);
        return ToDto(holiday, company.Name);
    }

    public async Task Delete(Guid organizationId, Guid companyId, Guid id)
    {
        CompanyHoliday holiday = await _companyHolidayHandler.GetByIdLight(organizationId, companyId, id);
        if (holiday == null)
            throw new NotFoundAppException("CompanyHoliday", id);

        await _companyHolidayHandler.Delete(holiday);
    }

    public async Task<GenerateCompanyHolidaysResult> Generate(Guid organizationId, Guid userId, Guid companyId, int year)
    {
        Company company = await EnsureCompanyExists(organizationId, companyId);

        List<(DateTimeOffset Date, string Name)> source = await ResolveHolidaySource(company.Country, year);
        if (source.Count == 0)
            throw new BusinessRuleException(
                ErrorCodes.HolidayCatalogNotDefinedForCountry,
                $"Praznici za državu '{company.Country}' nisu dostupni (ni vanjski servis ni ručna lista) — dodajte praznike ručno.");

        List<CompanyHoliday> existing = await _companyHolidayHandler.GetForCompanyByYear(organizationId, companyId, year);
        HashSet<DateTimeOffset> existingDates = existing.Select(h => h.Date).ToHashSet();

        List<CompanyHoliday> toCreate = new List<CompanyHoliday>();
        int skippedCount = 0;

        foreach ((DateTimeOffset date, string name) in source)
        {
            if (existingDates.Contains(date))
            {
                skippedCount++;
                continue;
            }

            // Isti izvor (vanjski API) zna vratiti dvije stavke za isti datum (npr. rijetko preklapanje državnih
            // praznika) — existingDates štiti od DB duplikata unutar VEĆ postojećih zapisa, ali ne i unutar
            // ovog istog poziva, zato eksplicitno paze na to ovdje umjesto da padne na unique constraint.
            existingDates.Add(date);

            toCreate.Add(new CompanyHoliday
            {
                Id = Guid.NewGuid(),
                OrganizationId = organizationId,
                CompanyId = companyId,
                Date = date,
                Name = name,
                IsAutoGenerated = true,
                CreatedAt = DateTimeOffset.UtcNow,
                CreatedBy = userId
            });
        }

        await _companyHolidayHandler.AddRange(toCreate);

        return new GenerateCompanyHolidaysResult
        {
            CreatedCount = toCreate.Count,
            SkippedCount = skippedCount,
            Created = toCreate.OrderBy(h => h.Date).Select(h => ToDto(h, company.Name)).ToList()
        };
    }

    /// <summary>Vanjski javni servis (nagerholidays.com, vidi IPublicHolidayApiClient) je PRVI pokušaj — pokriva
    /// sve države i sam računa pomične datume. Best-effort: null/prazan odgovor (mreža, timeout, država koju
    /// servis ne poznaje) tiho pada natrag na ručnu DefaultCompanyHolidays listu (trenutno samo HR).</summary>
    private async Task<List<(DateTimeOffset Date, string Name)>> ResolveHolidaySource(string countryCode, int year)
    {
        List<PublicHolidayResult> external = await _publicHolidayApiClient.GetPublicHolidays(year, countryCode);
        if (external != null && external.Count > 0)
            return external.Select(h => (h.Date, h.Name)).ToList();

        return DefaultCompanyHolidays.For(countryCode)
            .Select(d => (new DateTimeOffset(year, d.Month, d.Day, 0, 0, 0, TimeSpan.Zero), d.Name))
            .ToList();
    }

    private async Task<Company> EnsureCompanyExists(Guid organizationId, Guid companyId)
    {
        Company company = await _companyHandler.GetById(organizationId, companyId);
        if (company == null)
            throw new NotFoundAppException("Company", companyId);

        return company;
    }

    private static CompanyHolidayDto ToDto(CompanyHoliday holiday, string companyName)
    {
        return new CompanyHolidayDto
        {
            Id = holiday.Id.GetValueOrDefault(),
            CompanyId = holiday.CompanyId,
            CompanyName = companyName,
            Date = holiday.Date,
            Name = holiday.Name,
            IsAutoGenerated = holiday.IsAutoGenerated,
            CreatedAt = holiday.CreatedAt,
            CreatedBy = holiday.CreatedBy
        };
    }
}
